### ISSUE TITLE
return data

### ISSUE THREAD

**Issue by doubletaketech** [FuturesJS/forEachAsync#2]
I'm fairly new to async js.  I'm hoping you can help me. 
My forEachAsync calls a function that also contains a forEachAsync.  How do I return data from child loop to parent loop?
element contains a child array of photos that I have to convert to a base64 and return back as a array of photos with their new dataUrl. I need to update the photos in all of the docs.

hope this makes sense.  I'd appreciate any help.
Thanks,
Donnie 

``` javascript
forEachAsync(docs, function (next, element, index, array) {
  convertPics(element,next);
}).then(function () {

});

function convertPics(element,cb){
    var picJson = JSON.parse(element.photos)
    var basedir = process.env.CLOUD_DIR+'/';
    var arr = [];

    forEachAsync(picJson, function (next, p, index, array) {

        if (fs.existsSync(basedir + 'thumb_' + p.fileName)) {

            p.dataUrl = fs.readFileSync(basedir + 'thumb_' + p.fileName).toString('base64')

            arr.push(p);

        }
    }).then(function () {
        ???? how do I return the array so I can use it in the then of the parent call?
       cb() ???
    });


}
```

**Comment by coolaj86** [comment]
Delete the word 'async' (people seem to be confused by it) from your mind and replace it with 'event'.

JavaScript doesn't operate from one line to the next. It operates on events. Each time one event is complete you go to the next event. A mouse click is an event. A file read is an event. Every action that requires waiting is an event.

You cannot return an object to an event any more than you can make a sandwich 10 minutes from now and hand it to yourself 6 minutes ago.

I'm pretty sure this is what you're trying to do:

``` javascript
var basedir = process.env.CLOUD_DIR+'/';
var arr = [];

function doStuffWithDocs(docs) {
  // iterate through all docs
  return forEachAsync(docs, function (next, item) {
    convertPics(item, next);
  });
}

function convertPics(element, cb) {
  var picJson = JSON.parse(element.photos); // is this not already parsed?

  // iterate through each pic in each doc
  return forEachAsync(picJson, function (next, p) {
    fs.exists(basedir + 'thumb_' + p.fileName, function (exists) {
      if (!exists) {
        next();
        return;
      }

      fs.readFile(basedir + 'thumb_' + p.fileName, function (err, buffer) {
        if (err) {
          console.error('error reading thumb file:');
          console.error(err.stack);
          return;
        }

        p.dataUrl = buffer.toString('base64');
        arr.push(p);
        next();
      });
    });
  }).then(function () {
    cb();
  });
}

doStuffWithDocs(docs).then(function () {
    doStuffWithAllPics(arr);
})
```

Avoid anything `*Sync` at all costs because it's just gonna cause more confusion.

Events. Events. Events.

You generally don't "return" an object to a parent function (except for basic math functions), you call the next function you want to use (as if it were an event completion) with the result of whatever event you're working on.

Not line numbers, but rather time. It flows only in one direction.

I don't know if that helps...

So in a procedural language you do stuff like this

```
x = doStuff();
y = doMoreStuff(x);
z = doEvenMoreStuff(y);
```

in an event language you do this:

```
doStuff(); // this will call doMoreStuff() when it is done, which wil call doEvenMoreStuff() when it is done
```

**Comment by coolaj86** [comment]
Updated a few things.

**Comment by doubletaketech** [comment]
Wow! Thank you. This is exactly what I was trying to do.   Love the sandwich metaphor. :)   Clearly I have a lot to learn. Recommend any good books,videos, etc. for getting better at this?

**Comment by coolaj86** [comment]
Honestly, it's really tough to sort the good from the bad. So many different opinions and so few people teach JS as Event-Oriented. They try to cram it in with Object-Oriented, but it's just not the same.

My favorites are the Crockford vids. You won't understand them in the first go. I watched Function the Ultimate probably 3 or 4 times before I understood it:

https://www.youtube.com/playlist?list=PLlRSdZcxPj9_GK2i1KVvnZD9fVToABz3V

The learn JavaScript in 30 minutes series I've only watched a few of, but it was really good:

https://www.youtube.com/playlist?list=PL5C542E0286878FCB

**Comment by coolaj86** [comment]
You might also benefit from learning a little about ruby's EventMachine. This framework was contemporary to (and perhaps somewhat an inspiration for) node.js

https://vimeo.com/10849958

**Comment by doubletaketech** [comment]
excellent! I'll check them out.  Thank you!

**Comment by aluanhaddad** [comment]
@coolaj86 
> Honestly, it's really tough to sort the good from the bad. So many different opinions and so few people teach JS as Event-Oriented. They try to cram it in with Object-Oriented, but it's just not the same.
> 
> My favorites are the Crockford vids. You won't understand them in the first go. I watched Function the Ultimate probably 3 or 4 times before I understood it:

Firstly 👍 👍 👍 for recommending Crockford's lectures. They are by far the better resource for learning JavaScript. Even will all the new features being added at an ever faster cadence, his advice (pragmatism founded in experience and theory), practices (emphasis on correctness and readability), and teaching style (rigor, humor, and historical perspective) remain as relevant and valuable as ever.

Now regarding the whole issue of people trying to pretend that JavaScript is 
> Object-Oriented

I disagree slightly. It is a very real phenomenon and a pretty massive problem, but I would frame it differently. JavaScript _is_ Object-Oriented, but most people think that this implies a Java-like language, something very different. 

Regardless, my feeling is that the biggest problem here is overuse of classes, especially when such use involves conflating the notion of a JS value with that of a type. `instanceof` is a terrible thing.

> Events. Events. Events.
> 
> You generally don't "return" an object to a parent function (except for basic math functions), you call the next function you want to use (as if it were an event completion) with the result of whatever event you're working on.

This is where I break with you. Although in principal what you say is entirely correct, there are two significant problems with this approach. 

Firstly, it assumes that while one may (must?) _learn_ JavaScript as a largely event driven language and this is indeed fine, continuing to program in a callback based style makes code illegible and we can and should abstract from it where possible by leveraging both promise oriented libraries, like yours, and also by taking advantage of syntactic features like the `await` operator. If we have a suitable abstraction, we should only think in terms of events for things that are logically events and not, for example, when reading a file from beginning to end.

Secondly, you seem to be intimating (I may be misreading) that wanting to abstract over events and compose them and the values that they in turn bring into being in a value like manner is essentially applying a narrow, Object-Oriented mindset to JavaScript. I would argue it is if anything applying a _functional_ mindset, but why bother with paradematic comparisons. Let's keep using promises and the new ES primitives to make our code as readable as possible. Btw, this library works really nicely with `async` and `await`.
