### ISSUE TITLE
What is the purpose of having two npm modules for this which have the same name but different casing?

### ISSUE THREAD

**Issue by irond13** [FuturesJS/forEachAsync#3]
This makes it next to impossible to manipulate Linux builds on Macs (case insensitive) for projects which have transitive dependencies on both variants of the module.

**Comment by tilleul** [comment]
Same here on Windows. It forces you to install separately the module and forbids you to automatically update your packages. Have noticed problems with "hbs-utils" and "walk" which both use "forEachAsync" and/or "foreachasync" in different flavours ...

**Comment by coolaj86** [comment]
npm no longer allows cased module names. However, modules published with cased version names are preserved for compatibility.
